### ISSUE TITLE
Flagship Transaction: Needs Improvement

### ISSUE THREAD

**Issue by kpujjigit** [sentry-demos/ios#33]
- [x] Verify all auto-instrumentation is working as it should
- [x] Understand and mitigate the gap in the span view (See Image Below)
- [ ] Implement Custom Instrumentation (See Image Below) (get product guidance on "missing instrumentation")
- [x] Add client-side performance/profiling issue associated with a big span after the network call, like json encode on main thread

<img width="1030" alt="image" src="https://github.com/sentry-demos/ios/assets/103009467/9f510d25-ecfd-46cf-a926-192c99d00bea">

**Comment by armcknight** [comment]
Here's an example in the dashboard: https://demo.sentry.io/performance/mobile-ios:9cfb3fbe69534110bebcd64a7f36b730/?project=6249899&query=&referrer=performance-transaction-summary&statsPeriod=1h&transaction=EmpowerPlantViewController&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29

**Comment by realkosty** [comment]
Proposal from Oct 3 iOS Jam:
- put a custom span around all of readCurrentDirectory()
- make readCurrentDirectory run faster - 3-4 seconds instead of 8 seconds (adjust Performance Issue thresholds in Settings if necessary)
- Make DB calls longer (that's why they don't show up in profiling right now)
  - Use existing ["sleepy views"](https://github.com/sentry-demos/empower/pull/223) for that
- Consider making DB calls run on the same thread as the rest of the stuff - this allows us to tell a simpler demo story without concurrency.

**Comment by kpujjigit** [comment]
@armcknight how goes development on the above action items?

- Custom Instrumenting [readCurrentDirectory](https://github.dev/sentry-demos/ios/blob/f375dc51c827f97527b438bf783b1dedb6648c1e/EmpowerPlant/EmpowerPlantViewController.swift#L52-L53)

- Optimizing readCurrentDirectory

- Extending duration of DB Calls to appear in profiling

- Removing DB thread concurrency

**Comment by kahest** [comment]
@kpujjigit I didn't look into it closely, but I'm pretty sure that's the `readCurrentDirectory` - can you explain the purpose of this, and what the [custom instrumentation](https://github.com/sentry-demos/ios/issues/33#issuecomment-1758169325) should look like on the product?

**Comment by kpujjigit** [comment]
@kahest no further action needed here, this isn't a blocker so we'll leave it be. Thanks for chiming in.
